
server:
  port: 8010

spring:
  application:
    name: test-customer  #\u5FAE\u670D\u52A1\u540D\u79F0
  #\u914D\u7F6Enacos\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

ribbon:
  eager-load:
    enabled: true
    clients: test-spring-seq
